"""empty message

Revision ID: 4ce87b7566ff
Revises: 2049364ea0a6
Create Date: 2023-12-12 15:30:29.290199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ce87b7566ff'
down_revision = '2049364ea0a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ownership_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('percent_of_shares', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('percent_of_votes', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('missing_info_reason', sa.String(length=2000), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('submission_id', sa.Integer(), nullable=True))
        batch_op.drop_column('control_type')
        batch_op.add_column(sa.Column('control_type', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.create_foreign_key(None, 'submission', ['submission_id'], ['id'])
        batch_op.drop_column('control_percent')
        batch_op.drop_column('additional_text')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_name', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('citizenships_ex_ca', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('tax_number', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('competency', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('date_of_birth')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('other', 'standard', name='submissiontype'), nullable=True))
        batch_op.drop_column('state')
        batch_op.add_column(sa.Column('effective_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('submitted_datetime', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('submitted_date')

    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Enum('other', 'standard', name='submissiontype'), autoincrement=False, nullable=True))
        batch_op.drop_column('state')
        batch_op.add_column(sa.Column('effective_date', sa.Date(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('submitted_datetime', sa.DateTime(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('submitted_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', postgresql.ENUM('other', 'standard', name='submissiontype'), autoincrement=False, nullable=True))
        batch_op.drop_column('type')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', postgresql.ENUM('other', 'standard', name='submissiontype'), autoincrement=False, nullable=True))
        batch_op.drop_column('type')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('address')
        batch_op.drop_column('competency')
        batch_op.drop_column('tax_number')
        batch_op.drop_column('citizenships_ex_ca')
        batch_op.drop_column('email')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('preferred_name')

    with op.batch_alter_table('ownership_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_text', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('control_percent', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('control_type')
        batch_op.add_column(sa.Column('control_type', sa.String(length=50), nullable=False))
        batch_op.drop_column('submission_id')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('missing_info_reason')
        batch_op.drop_column('percent_of_votes')
        batch_op.drop_column('percent_of_shares')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
