"""empty message

Revision ID: 80c36ed40ebb
Revises: 247ab32b10ec
Create Date: 2024-01-25 15:48:51.940453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c36ed40ebb'
down_revision = '247ab32b10ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###
