"""empty message

Revision ID: f812f2754dd5
Revises: 8d8279a86def
Create Date: 2024-10-11 09:51:07.594057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f812f2754dd5'
down_revision = '8d8279a86def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('business_identifier', sa.String(), nullable=False),
    sa.Column('information_to_omit', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('individual_at_risk', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('reasons', sa.String(), nullable=False),
    sa.Column('completing_party', sa.Enum('SI', 'REPRESENTATIVE', name='completingparty'), nullable=False),
    sa.Column('completing_name', sa.String(), nullable=False),
    sa.Column('completing_email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_business_identifier'), ['business_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_uuid'), ['uuid'], unique=False)

    op.create_table('request_history',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.Uuid(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('email', sa.String(), autoincrement=False, nullable=False),
    sa.Column('birthdate', sa.Date(), autoincrement=False, nullable=False),
    sa.Column('business_identifier', sa.String(), autoincrement=False, nullable=False),
    sa.Column('information_to_omit', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=False),
    sa.Column('individual_at_risk', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=False),
    sa.Column('reasons', sa.String(), autoincrement=False, nullable=False),
    sa.Column('completing_party', sa.Enum('SI', 'REPRESENTATIVE', name='completingparty'), autoincrement=False, nullable=False),
    sa.Column('completing_name', sa.String(), autoincrement=False, nullable=False),
    sa.Column('completing_email', sa.String(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DateTime(), autoincrement=False, nullable=False),
    sa.Column('version', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('request_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_history_business_identifier'), ['business_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_history_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_history_uuid'))
        batch_op.drop_index(batch_op.f('ix_request_history_business_identifier'))

    op.drop_table('request_history')
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_uuid'))
        batch_op.drop_index(batch_op.f('ix_request_business_identifier'))

    op.drop_table('request')
    op.execute('DROP TYPE completingparty')
    # ### end Alembic commands ###
