"""empty message

Revision ID: f586cb178aff
Revises: da4fbdb48338
Create Date: 2024-01-15 14:13:36.861706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f586cb178aff'
down_revision = 'da4fbdb48338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_identifier', sa.String(length=255), nullable=True))
        batch_op.drop_column('submitted_datetime')

    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_identifier', sa.String(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('submitted_datetime')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('business_identifier')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.drop_column('business_identifier')

    # ### end Alembic commands ###
