"""empty message

Revision ID: bcce6df0c72a
Revises: f812f2754dd5
Create Date: 2025-02-11 11:38:09.362521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcce6df0c72a'
down_revision = 'f812f2754dd5'
branch_labels = None
depends_on = None

new_submissiontype_options = ('annual', 'change', 'initial')
old_submissiontype_options = ('other', 'standard')

new_submissiontype_enum = sa.Enum(*new_submissiontype_options, name='submissiontype')
old_submissiontype_enum = sa.Enum(*old_submissiontype_options, name='submissiontype')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.drop_column('type')
    
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('type')
    
    op.execute('DROP TYPE submissiontype')
    
    new_submissiontype_enum.create(op.get_bind())

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', new_submissiontype_enum, nullable=True))
        batch_op.add_column(sa.Column('ledger_reference_number', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('ledger_updated', sa.Boolean(), nullable=True, default=False))
        batch_op.create_unique_constraint(None, ['ledger_reference_number'])
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('effective_date')

    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        # batch_op.drop_column('type')
        batch_op.add_column(sa.Column('type', new_submissiontype_enum, nullable=True))
        batch_op.add_column(sa.Column('ledger_reference_number', sa.Uuid(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ledger_updated', sa.Boolean(), autoincrement=False, nullable=True))
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('effective_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.drop_column('type')
    
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('type')
    
    op.execute('DROP TYPE submissiontype')
    
    old_submissiontype_enum.create(op.get_bind())

    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', old_submissiontype_enum, nullable=True))
        batch_op.add_column(sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('ledger_updated')
        batch_op.drop_column('ledger_reference_number')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', old_submissiontype_enum, nullable=True, default='other'))
        batch_op.add_column(sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('ledger_updated')
        batch_op.drop_column('ledger_reference_number')

    # ### end Alembic commands ###
