"""empty message

Revision ID: ebd16663238c
Revises: 91131af53886
Create Date: 2025-06-02 15:12:52.751521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebd16663238c'
down_revision = '91131af53886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completing_address', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('completing_phone', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    op.execute("UPDATE request SET completing_address = '{}' WHERE completing_address IS NULL")
    op.execute("UPDATE request SET completing_phone = '{}' WHERE completing_phone IS NULL")

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('completing_address', nullable=False)
        batch_op.alter_column('completing_phone', nullable=False)

    with op.batch_alter_table('request_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completing_address', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('completing_phone', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))

    op.execute("UPDATE request_history SET completing_address = '{}' WHERE completing_address IS NULL")
    op.execute("UPDATE request_history SET completing_phone = '{}' WHERE completing_phone IS NULL")

    with op.batch_alter_table('request_history', schema=None) as batch_op:
        batch_op.alter_column('completing_address', nullable=False)
        batch_op.alter_column('completing_phone', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_history', schema=None) as batch_op:
        batch_op.drop_column('completing_phone')
        batch_op.drop_column('completing_address')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('completing_phone')
        batch_op.drop_column('completing_address')

    # ### end Alembic commands ###
