"""empty message

Revision ID: 91c9edf84407
Revises: 07b4b6b9544c
Create Date: 2025-06-06 11:09:29.841994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91c9edf84407'
down_revision = '07b4b6b9544c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_identifiers', postgresql.ARRAY(sa.String()), nullable=False))
        batch_op.drop_index('ix_request_business_identifier')
        batch_op.create_index(batch_op.f('ix_request_business_identifiers'), ['business_identifiers'], unique=False)
        batch_op.drop_column('business_identifier')

    with op.batch_alter_table('request_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_identifiers', postgresql.ARRAY(sa.String()), autoincrement=False, nullable=False))
        batch_op.drop_index('ix_request_history_business_identifier')
        batch_op.create_index(batch_op.f('ix_request_history_business_identifiers'), ['business_identifiers'], unique=False)
        batch_op.drop_column('business_identifier')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_request_history_business_identifiers'))
        batch_op.create_index('ix_request_history_business_identifier', ['business_identifier'], unique=False)
        batch_op.drop_column('business_identifiers')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_request_business_identifiers'))
        batch_op.create_index('ix_request_business_identifier', ['business_identifier'], unique=False)
        batch_op.drop_column('business_identifiers')

    # ### end Alembic commands ###
