"""empty message

Revision ID: 2049364ea0a6
Revises: 191f8d1ddc48
Create Date: 2023-10-03 12:50:15.811699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2049364ea0a6'
down_revision = '191f8d1ddc48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('uuid', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('family_name', sa.String(length=100), nullable=True),
    sa.Column('given_name', sa.String(length=100), nullable=True),
    sa.Column('patronymic_name', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_permanent_resident', sa.Boolean(), nullable=True),
    sa.Column('is_canadian_citizen', sa.Boolean(), nullable=True),
    sa.Column('is_canadian_tax_resident', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_full_name'), ['full_name'], unique=False)

    op.create_table('ownership_details',
    sa.Column('business_identifier', sa.String(length=300), nullable=False),
    sa.Column('control_type', sa.String(length=50), nullable=False),
    sa.Column('control_percent', sa.Integer(), nullable=False),
    sa.Column('additional_text', sa.String(length=2000), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ownership_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ownership_details_business_identifier'), ['business_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ownership_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ownership_details_business_identifier'))

    op.drop_table('ownership_details')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_full_name'))

    op.drop_table('persons')
    # ### end Alembic commands ###
