export enum InputFieldsE {
  COULD_NOT_PROVIDE_MISSING_INFO = 'couldNotProvideMissingInfo',
  MISSING_INFO_REASON = 'missingInfoReason',
  NAME = 'name',
  FULL_NAME = 'name.fullName',
  PREFERRED_NAME = 'name.preferredName',
  CONTROL_OF_SHARES = 'controlOfShares',
  CONTROL_OF_VOTES = 'controlOfVotes',
  CONTROL_OF_DIRECTORS = 'controlOfDirectors',
  EMAIL = 'email',
  ADDRESS = 'address',
  ADDRESS_LINE1 = 'address.line1',
  ADDRESS_LINE2 = 'address.line2',
  ADDRESS_POSTAL_CODE = 'address.postalCode',
  ADDRESS_CITY = 'address.city',
  ADDRESS_REGION = 'address.region',
  ADDRESS_COUNTRY = 'address.country',
  ADDRESS_LOCATION_DESCRIPTION = 'address.locationDescription',

  MAILING_ADDRESS = 'mailingAddress',
  MAILING_ADDRESS_LINE1 = 'mailingAddress.line1',
  MAILING_ADDRESS_LINE2 = 'mailingAddress.line2',
  MAILING_ADDRESS_POSTAL_CODE = 'mailingAddress.postalCode',
  MAILING_ADDRESS_CITY = 'mailingAddress.city',
  MAILING_ADDRESS_REGION = 'mailingAddress.region',
  MAILING_ADDRESS_COUNTRY = 'mailingAddress.country',
  MAILING_ADDRESS_LOCATION_DESCRIPTION = 'mailingAddress.locationDescription',

  BIRTH_DATE = 'birthDate',
  CITIZENSHIPS = 'citizenships',
  TAX = 'tax',
  TAX_NUMBER = 'tax.number',
  IS_TAX_RESIDENT = 'isTaxResident',
  DETERMINATION_OF_INCAPACITY = 'determinationOfIncapacity',
  PHONE_NUMBER = 'phoneNumber',
  EFFECTIVE_DATES = 'effectiveDates'
}
