steps:
  # setup .env
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: btr-web/btr-main-app
    entrypoint: bash
    args: ['-c', 'cp .env.example .env']
  # install deps
  - name: 'node:20.6.1'
    dir: btr-web
    env:
      - 'VUE_APP_ADDRESS_COMPLETE_KEY=$_VUE_APP_ADDRESS_COMPLETE_KEY'
    script: |
      #!/usr/bin/env bash
      npm install --global pnpm
      pnpm install
      pnpm build:btr-main-app
  # mv dist folder root
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: btr-web
    entrypoint: bash
    args: ['-c', 'mv btr-main-app/dist .']
  # deploy
  - name: gcr.io/yfthig-dev/firebase
    args:
      - '-c'
      - >-
        firebase hosting:channel:deploy --project=yfthig-dev PR-$_PR_NUMBER >
        /workspace/firebase-deploy.txt
    dir: btr-web/btr-main-app
    entrypoint: bash
  # post the temp url in the PR
  - name: gcr.io/cloud-builders/curl
    args:
      - '-c'
      - >
        # Read from "/workspace"

        cat /workspace/firebase-deploy.txt

        url=`cat /workspace/firebase-deploy.txt| grep 'Channel URL' | grep -Eo
        "https://[a-zA-Z0-9./?=_%:-]*"`

        echo "this is the body:"

        echo '{"body": "Temporary Url for review:'"$url"'"}'

        curl -X POST \

        https://api.github.com/repos/bcgov/business-transparency-registry/issues/$_PR_NUMBER/comments
        \

        --header "Authorization: Token $$TOKEN" \

        --header "Accept: application/vnd.github.v3+json" \

        --data-binary '{"body": "Temporary Url for review: '"$url"'"}'
    dir: btr-web/btr-main-app
    id: Update the PR
    entrypoint: bash
    secretEnv:
      - TOKEN
options:
  dynamicSubstitutions: true
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/token-pr-review/versions/latest
      env: TOKEN
