name: BTR UI Main CD

on:
  push:
    branches:
      - main
    paths:
      - "btr-web/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  btr-ui-main-cd:
    permissions:
      contents: "write"
      id-token: "write"
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-cd.yaml@main
    with:
      target: ${{ inputs.environment }}
      node_version: 20
      working_directory: "./btr-web"
      package_name: "btr-main-app"
      app_name: "btr-ui"
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
