name: BTR UI CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "btr-web/**"

defaults:
  run:
    shell: bash

jobs:
  setup-job:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        project: ["btr-main-app", "btr-common-components", "btr-layouts"]
      fail-fast: false

    defaults:
      run:
        working-directory: btr-web/${{ matrix.project }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm run lint


  unit-testing:
    needs: setup-job
    runs-on: ubuntu-24.04
    
    strategy:
      matrix:
        project: ["btr-main-app", "btr-common-components", "btr-layouts"]
      fail-fast: false

    defaults:
      run:
        working-directory: btr-web/${{ matrix.project }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Set basic env
        run: |
          cp .env.example .env

      - name: Run unit tests
        run: pnpm test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./btr-web/btr-main-app/coverage/clover.xml
          flags: btr-ui
          name: codecov-btr-ui
          fail_ci_if_error: false

  cypress-e2e-test:
    needs: setup-job
    runs-on: ubuntu-24.04
    
    strategy:
      matrix:
        project: ["btr-main-app", "btr-common-components", "btr-layouts"]
      fail-fast: false

    defaults:
      run:
        working-directory: btr-web/${{ matrix.project }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - name: Install dependencies
        run: pnpm install

      - name: Set basic env
        working-directory: btr-web/${{ matrix.project }}
        run: |
          cp .env.example .env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          working-directory: btr-web/${{ matrix.project }}
          build: pnpm run build:local
          start: pnpm start

  
  build-check:
    needs: setup-job
    runs-on: ubuntu-24.04
    
    strategy:
      matrix:
        project: ["btr-main-app", "btr-common-components", "btr-layouts"]
      fail-fast: false

    defaults:
      run:
        working-directory: btr-web/${{ matrix.project }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build Check
        run: pnpm build

  build-check-for-deployment:
    needs: setup-job
    runs-on: ubuntu-24.04
    
    defaults:
      run:
        working-directory: btr-web
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build Check
        run: pnpm build:btr-main-app