name: BTR UI CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "btr-web/**"

defaults:
  run:
    shell: bash

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        project: ["btr-main-app", "btr-common-components", "btr-layouts"]
      fail-fast: false

    defaults:
      run:
        working-directory: btr-web/${{ matrix.project }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run linting
        run: pnpm run lint


  unit-testing:
    needs: setup-job
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        project: ["btr-main-app", "btr-common-components", "btr-layouts"]
      fail-fast: false

    defaults:
      run:
        working-directory: btr-web/${{ matrix.project }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Set basic env
        run: |
          cp .env.example .env

      - name: Run unit tests
        run: pnpm test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./btr-web/btr-main-app/coverage/clover.xml
          flags: btr-ui
          name: codecov-btr-ui
          fail_ci_if_error: false

  cypress-e2e-test:
    needs: setup-job
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        project: ["btr-main-app", "btr-common-components", "btr-layouts"]
      fail-fast: false

    defaults:
      run:
        working-directory: btr-web/${{ matrix.project }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Set basic env
        working-directory: btr-web/${{ matrix.project }}
        run: |
          cp .env.example .env

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          working-directory: btr-web/${{ matrix.project }}
          build: pnpm run build:local
          start: pnpm start
  
  build-check:
    needs: setup-job
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        project: ["btr-main-app", "btr-common-components", "btr-layouts"]
      fail-fast: false

    defaults:
      run:
        working-directory: btr-web/${{ matrix.project }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build Check
        run: pnpm build

  build-check-for-deployment:
    needs: setup-job
    runs-on: ubuntu-20.04
    
    defaults:
      run:
        working-directory: btr-web
  
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build Check
        run: pnpm build:btr-main-app